language: cpp

dist: trusty

matrix:
  include:

    - os: osx
      compiler: gcc
      env: COMPILER='g++ -std=c++11 -O2'

    - os: osx
      compiler: clang
      env: COMPILER='clang++ -std=c++11 -O2'

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - g++-5
      env: COMPILER='g++-5 -std=c++11 -O2'

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages: 
            - g++-8
      env: COMPILER='g++-8 -std=c++17 -O2'

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: 
            - llvm-toolchain-trusty-3.9
          packages:
            - clang-3.9
      env: COMPILER='clang++-3.9 -std=c++11 -O2'

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: 
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env: COMPILER='clang++-6.0 -std=c++17 -O2'

script:
  - cd test
  - mkdir build
  - make build/momo
  - build/momo
