language: cpp

matrix:
  include:

    - os: linux
      compiler: gcc
      env: COMPILER='g++ -std=c++11 -O2 -Wno-unused-variable'

    - os: linux
      compiler: clang
      env: COMPILER='clang++ -std=c++11 -O2 -Wno-c++17-extensions'

    - os: linux
      compiler: clang
      env: COMPILER='clang++ -std=c++17 -O2'

script:
  - cd test
  - mkdir build
  - make build/momo
  - build/momo
