language: cpp

matrix:
  include:

    - os: osx
      osx_image: xcode8.3
      compiler: clang
      env: COMPILER='clang++ -std=c++11 -O2 -Wno-c++1z-extensions'

    - os: osx
      osx_image: xcode11
      compiler: clang
      env: COMPILER='clang++ -std=c++17 -O2'

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER='g++-4.9 -std=c++11 -O2'

    - os: linux
      dist: xenial
      compiler: gcc
      # gcc 5.4.0
      env: COMPILER='g++ -std=c++17'

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER='g++-7 -std=c++17 -O3 -DMOMO_USE_SAFE_MAP_BRACKETS -DMOMO_USE_UNORDERED_HINT_ITERATORS'

    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env: COMPILER='g++-9 -std=c++17 -O2'

    - os: linux
      dist: precise
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER='clang++-3.6 -std=c++11 -O2'

    - os: linux
      dist: precise
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
      env: COMPILER='clang++-3.9 -std=c++1z -O3 -DMOMO_USE_SAFE_MAP_BRACKETS -DMOMO_USE_UNORDERED_HINT_ITERATORS'

    - os: linux
      dist: xenial
      compiler: clang
      # clang 7.0.0
      env: COMPILER='clang++ -std=c++17 -O2'

    - os: linux
      dist: xenial
      compiler: clang
      # clang 7.0.0
      env: COMPILER='clang++ -std=c++17 -g -fsanitize=address,undefined'

script:
  - cd test
  - mkdir build
  - make build/momo
  - build/momo
